import AppKit

/// A full copy of a pasteboard (every item, every type) so it can be put back after our paste.
struct PasteboardSnapshot {
    struct Item {
        var entries: [(type: NSPasteboard.PasteboardType, data: Data)]
    }

    var items: [Item]
    /// The original came from a password manager (or similar) that marked it concealed.
    var containsConcealed: Bool

    // nspasteboard.org markers: clipboard managers skip transient/concealed/auto-generated content.
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// File promises can't be round-tripped faithfully.
    private static let unrestorable: Set<String> = [
        "com.apple.NSFilePromiseItemMetaData",
        "com.apple.pasteboard.promised-file-url",
        "com.apple.pasteboard.promised-file-content-type",
    ]

    /// Reads every type of every item (which makes lazy providers in other apps materialize their data).
    /// Returns nil when the contents are too large or can't be restored faithfully.
    static func capture(_ pasteboard: NSPasteboard, maxBytes: Int = 20 * 1024 * 1024) -> PasteboardSnapshot? {
        guard let pasteboardItems = pasteboard.pasteboardItems else {
            return PasteboardSnapshot(items: [], containsConcealed: false)
        }
        var total = 0
        var concealed = false
        var items: [Item] = []
        for item in pasteboardItems {
            var entries: [(type: NSPasteboard.PasteboardType, data: Data)] = []
            for type in item.types {
                if unrestorable.contains(type.rawValue) { return nil }
                if type == concealedType { concealed = true }
                guard let data = item.data(forType: type) else { continue }
                total += data.count
                if total > maxBytes { return nil }
                entries.append((type, data))
            }
            items.append(Item(entries: entries))
        }
        return PasteboardSnapshot(items: items, containsConcealed: concealed)
    }

    func restore(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored: [NSPasteboardItem] = items.map { item in
            let copy = NSPasteboardItem()
            for entry in item.entries { copy.setData(entry.data, forType: entry.type) }
            return copy
        }
        _ = pasteboard.writeObjects(restored)
    }

    /// macOS 15.4+ pasteboard privacy: a programmatic read that isn't a paste may alert the user, so the
    /// backup read is skipped unless access is already allowed.
    static func mayRead(_ pasteboard: NSPasteboard) -> Bool {
        switch pasteboard.accessBehavior {
        case .alwaysAllow, .default: true
        case .ask, .alwaysDeny: false
        @unknown default: false
        }
    }
}
