import AppKit

/// nspasteboard.org markers on what the app puts on the clipboard: clipboard managers skip transient, concealed and
/// auto-generated content, and the source names the app.
enum PasteboardMarkers {
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
}
